language: node_js
os: linux
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - "8.9.0"
  - "8.16.0"
  - "9.11.2"
  - "10.16.0"
  - "lts/*"
  - node

install: npm install

stages:
  - name: lint
  - name: coverage
  - name: release
    if: branch = master && type NOT IN (pull_request)
  - name: docs
    if: branch = master && type NOT IN (pull_request)

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm test
    - stage: coverage
      script: npm run coverage
    - stage: release
      node_js: node
      deploy:
        provider: script
        cleanup: false
        script:
          - npx semantic-release
    - stage: docs
      script:
        - chmod +x ./.github/update_docs.sh
        - ./.github/update_docs.sh
